language: php
php:
  - '8.1.27'

before_install:
  - cd ../ && composer self-update 2.7.1 && cd -

install:
  - pecl install ast-1.0.16
  - composer install --prefer-dist --no-interaction --dev

script:
    - ./ci/style.php
    - ./ci/phan.php

notifications:
    email:
        on_success: never

sudo: false
dist: focal
