language: php
php:
  - '7.4.7'

install:
  - pecl install ast-1.0.3
  - cd ../ && composer self-update 1.6.4 && cd -
  - composer install --prefer-dist --no-interaction --dev

script:
    - ./ci/style.php
    - ./ci/phan.php

notifications:
    email:
        on_success: never

sudo: false
