language: php
php:
    - '7.0.16'

install:
  - pecl install ast-0.1.7
  - composer self-update
  - composer install --prefer-dist --no-interaction --dev

script:
    - ./ci/style.php
    - ./ci/phan.php

notifications:
    email:
        on_success: never

sudo: false
